### ISSUE TITLE
should `col_select()` bypass the mandatory same column number check

### ISSUE THREAD

**Issue by ginolhac** [r-lib/vroom#120] opened 2019-05-28 12:39 UTC
Hi,

`vroom` when binding several datasets takes care of checking columns consistency and I appreciate that. However, since there is this **great** feature of `col_select()` shouldn't the following work?

We should be able to bind a subset of columns as long as the col names and col types are consistent across datasets in my opinion

``` r
library("dplyr", warn.conflicts = FALSE)

by_cyl <- group_split(mtcars, cyl)
#add one col to last tibble
by_cyl[[3]] <- mutate(by_cyl[[3]], garbage = "garb")

purrr::iwalk(
 by_cyl, 
 ~ readr::write_tsv(.x, glue::glue("mtcars_{.y}.tsv.gz"))
)
fs::dir_ls(glob = "*tsv.gz") %>%
  vroom::vroom(col_select = c(mpg, wt))
#> Error: Files must all have 11 columns:
#> * File 3 has 12 columns
```

<sup>Created on 2019-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment] 2019-05-28 13:01
Thanks! I can confirm the issue and this looks like a bug.

**Comment by jimhester** [comment] 2019-05-28 13:15
Oh wait, now I re-read the issue I actually am not sure I agree that this is an issue.

I see how it could be useful, but I am not really sure this should be allowed, it seems pretty dangerous if the column names are not read properly.

**Comment by ginolhac** [comment] 2019-05-28 13:21
I see your point, my case is some sequencing summary, but some files were generated with a different software version, more recent output one more column. I'd like to compare the ones that are common.
But, I guess you recommend to discard outside of R the extra column

**Comment by jimhester** [comment] 2019-05-28 13:23
Yeah I can understand how this could be useful, maybe we could add an option to skip the consistency check...

**Comment by ginolhac** [comment] 2019-05-28 13:25
Actually I see pros and cons for adding an option or keeping a strict usage. I am not pushing for anything, maybe just a message like `make sure each file have the same number and column types` is enough. I am already more than happy with `vroom`

**Comment by ginolhac** [comment] 2019-05-29 11:34
whatever your final decision is, the behavior should be the same for `col_only()`

```r
fs::dir_ls(glob = "*tsv.gz") %>%
  vroom(col_types = cols_only(mpg = "d", wt = "d"))
#> Error: Files must all have 11 columns:
#> * File 3 has 12 columns
```

**Comment by jimhester** [comment] 2019-06-06 13:50
I am going to close this for now, we can revisit if if down the line we have more robust column matching across multiple files.

**Closed by jimhester** 2019-06-06 13:50 UTC
Labels: feature

**Comment by martgnz** [comment] 2020-05-10 22:15
Hello, do you think there could be a way to revisit this? I'm loading a large dataset distributed on hundreds of files. Annoyingly, some of them have one extra column at the end, which I'm really not interested in and make vroom fail.

Maybe the consistency check could be skipped if the user wants to?

**Comment by martgnz** [comment] 2020-05-10 22:43
It'd be nice to be able to skip the column name check too. The dataset I'm working with adds that extra column before the last one, so they fail that test as well. Would that have other ramifications?

For me it doesn't matter having different data in those columns as I'm not interested in them, I will filter them out in my analysis. I know it's not really great, though.

**Comment by Aariq** [comment] 2026-05-06 22:42
Just wanted to chime in and say that this indeed would be useful, especially because I suspect it would be a lot more efficient than `list_of_csv_paths |> map(\(x) read_csv(x, col_select = ...)) |> list_rbind()` for when all the CSVs have some shared columns but some have additional columns.
