### ISSUE TITLE
Can't delete files after read by vroom in R session

### ISSUE THREAD

**Issue by ericbrownaustin** [r-lib/vroom#177] opened 2019-08-15 15:18 UTC
I read some files using vroom in R and after reading them, I received a windows File in Use error.  Is this the expected behavior and if so, how can remove the files without dropping the R session?

![image](https://user-images.githubusercontent.com/11723172/63105335-39368100-bf46-11e9-9193-dd4b4752b796.png)

**Comment by jimhester** [comment] 2019-08-15 16:38
The error you are showing is a TAR file, which vroom does not read, please provide full details of what you are actually doing.

**Comment by ericbrownaustin** [comment] 2019-08-15 17:13
Same results for a tsv file which was read without issue.

![image](https://user-images.githubusercontent.com/11723172/63112525-10b68300-bf56-11e9-9e51-7e4c800d8795.png)

**Comment by jimhester** [comment] 2019-08-15 21:07
vroom reads files lazily, the file is initially memory mapped and remains open until all the values in the file have been read in it.

If you don't want the lazy reading you can use `vroom(altrep_opts = FALSE)` to read the file eagerly.

**Comment by cucumberry** [comment] 2019-09-18 13:19
I've got this issue too. If you want the general behaviour of vroom but just want to delete one file, is there a way to manually close it?

**Comment by rplati** [comment] 2019-12-02 13:33
Same issue here. `vroom(altrep_opts = FALSE)` does not seem to help. The only way to delete the file I’ve found is to close the R-session then delete it manually.

Would like to use vroom in a plumber API to read a csv file that arrives in multipart/form (parsed using Rook). Not being able to delete temporary files means the disk will fill up unless the service is reset periodically. Will need to use readr for now.

Minimal example:
```
tmpFile<-file.path(tempdir(), "iris.csv")
vroom_write(iris, tmpFile, delim = ",", quote="all")
irisVrm <- vroom(tmpFile, altrep_opts = FALSE)
rm(irisVrm)  # even deleting the object doesnt help
file.remove(tmpFile)
```

**Comment by jimhester** [comment] 2019-12-02 21:51
I can reproduce this, it was due to a very stupid bug in the code I used to check if a file ends with a newline. It is now fixed.

**Closed** 2019-12-02 21:50 UTC
Labels: reprex

**Comment by christian-beckmann** [comment] 2021-03-03 15:37
Sadly this bug appears now in version 1.4.0. Can you bisect it?

**Comment by jimhester** [comment] 2021-03-03 16:56
@christian-beckmann if you think there is an issue you will need to open a new issue with a reproducible example that demonstrates it.
