### ISSUE TITLE
vroom introduces missing data

### ISSUE THREAD

**Issue by jonaszierer** [r-lib/vroom#190] opened 2019-12-12 11:42 UTC
numbers that are approx smaller than 1e-60 are set to Inf by vroom:

```
require(tidyverse)
require(vroom)

d <- tibble(a = letters[1:10],
            b = seq(from = 10, to = 100, by = 10) %>% map_dbl(~10**(-.x)))

            
write_csv(d, "test.csv")

x1 <- read_csv("test.csv")
x2 <- vroom("test.csv")
```

`x1` is the data as expected while in `x2` all values smaller than 1-60 are `Inf`

vroom is version 1.0.2 and R is 3.6.1

**Comment by jimhester** [comment] 2019-12-12 14:05
This is a duplicate of https://github.com/r-lib/vroom/issues/164, it is fixed in the devel version of vroom

**Closed by jimhester** 2019-12-12 14:05 UTC
