### ISSUE TITLE
when specifying col_types, empty strings in a .CSV are read as NA for double, but zero for integer 

### ISSUE THREAD

**Issue by kallom** [r-lib/vroom#137] opened 2019-06-20 15:18 UTC

**Comment by kallom** [comment] 2019-06-20 15:22
`> vroom("x,y,z\nA,2,2\nB,,4\nC,6,6\n", col_types = list(col_character(), col_integer(), col_double()))
# A tibble: 3 x 3                                                                                                                                 
  x         y     z
  <chr> <int> <dbl>
1 A         2     2
2 B         0     4
3 C         6     6
> vroom("x,y,z\nA,2,2\nB,,4\nC,6,6\n", col_types = list(col_character(), col_double(), col_integer()))
# A tibble: 3 x 3                                                                                                                                 
  x         y     z
  <chr> <dbl> <int>
1 A         2     2
2 B        NA     4
3 C         6     6`

vroom_1.0.1 - sorry, might be duplicate

**Comment by jimhester** [comment] 2019-06-20 17:44
This is a duplicate of #135, already fixed

**Closed by jimhester** 2019-06-20 17:44 UTC
