### ISSUE TITLE
force paths to be UTF-8 encoded for Windows

### ISSUE THREAD

**Issue by kevinushey** [r-lib/vroom#401] opened 2022-02-04 19:57 UTC
With the upcoming release of RStudio, which defaults to a UTF-8 code page, `vroom` fails to read files. An issue was originally filed [here](https://github.com/rstudio/rstudio/issues/10507), but this is an MRE using a daily build of RStudio on Windows.

```
library(vroom)
path <- file.path(tempdir(), "mtcärs.csv")
write.csv(mtcars, path)
vroom(path)
```

When run in the latest version of RStudio, I see:

```
> vroom(path)
Warning in file(con, "rb") :
  cannot open file 'C:/Users/kevin/AppData/Local/Temp/Rtmp2LiZNQ/mtcï¿½rs.csv': No such file or directory
```

I believe the issue could be dodged by ensuring the paths are `enc2utf8()`-ed, so they're appropriately converted from UTF-8 on open.

```
> head(vroom(enc2utf8(path)))
New names:                                                                                                                                               
* `` -> ...1
Rows: 32 Columns: 12
-- Column specification ----------------------------------------------------------------------------------------------
Delimiter: ","
chr  (1): ...1
dbl (11): mpg, cyl, disp, hp, drat, wt, qsec, vs, am, gear, carb

i Use `spec()` to retrieve the full column specification for this data.
i Specify the column types or set `show_col_types = FALSE` to quiet this message.
# A tibble: 6 x 12
  ...1                mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
  <chr>             <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1 Mazda RX4          21       6   160   110  3.9   2.62  16.5     0     1     4     4
2 Mazda RX4 Wag      21       6   160   110  3.9   2.88  17.0     0     1     4     4
3 Datsun 710         22.8     4   108    93  3.85  2.32  18.6     1     1     4     1
4 Hornet 4 Drive     21.4     6   258   110  3.08  3.22  19.4     1     0     3     1
5 Hornet Sportabout  18.7     8   360   175  3.15  3.44  17.0     0     0     3     2
6 Valiant            18.1     6   225   105  2.76  3.46  20.2     1     0     3     1
```

---

```
> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 65001

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] vroom_1.5.7.9000 readr_2.1.2     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.13  magrittr_2.0.1   hms_1.1.1        tidyselect_1.1.1 bit_4.0.4        archive_1.1.4   
 [7] R6_2.5.1         rlang_0.4.12     fansi_1.0.2      tools_4.1.2      parallel_4.1.2   utf8_1.2.2      
[13] cli_3.1.1        withr_2.4.3      ellipsis_0.3.2   bit64_4.0.5      tibble_3.1.6     lifecycle_1.0.1 
[19] crayon_1.4.2     purrr_0.3.4      tzdb_0.2.0       vctrs_0.3.8      curl_4.3.2       glue_1.6.0      
[25] compiler_4.1.2   pillar_1.7.0     pkgconfig_2.0.3 
```

**Comment by jennybc** [comment] 2022-02-04 20:06
Duplicate of #394

**Closed by jennybc** 2022-02-04 20:06 UTC
