### ISSUE TITLE
README multifile `.tsv` example hangs

### ISSUE THREAD

**Issue by patr1ckm** [r-lib/vroom#102] opened 2019-05-09 13:44 UTC
The multifile tsv example from the README hangs indefinitely in both Rstudio (1.2) and the R command line without setting `progress=FALSE`. 

```
library(nycflights13)
purrr::iwalk(
  split(flights, flights$carrier),
  ~ vroom::vroom_write(.x, glue::glue("flights_{.y}.tsv"), delim = "\t")
)
files <- fs::dir_ls(glob = "flights*tsv")
vroom(file = files, delim = '\t')
```

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] vroom_1.0.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1       fansi_0.4.0      assertthat_0.2.1 utf8_1.1.4       packrat_0.5.0   
 [6] crayon_1.3.4     magrittr_1.5     pillar_1.3.1     cli_1.1.0        rlang_0.3.4     
[11] rstudioapi_0.10  fs_1.3.0         tools_3.6.0      glue_1.3.1       purrr_0.3.2     
[16] parallel_3.6.0   compiler_3.6.0   pkgconfig_2.0.2  tidyselect_0.2.5 tibble_2.1.1  
```

**Comment by jimhester** [comment] 2019-05-09 15:27
This is a duplicate of https://github.com/r-lib/vroom/issues/98, it is now fixed in the development version, we will have a CRAN release soon.

**Closed by jimhester** 2019-05-09 15:27 UTC
