### ISSUE TITLE
The size of the connection buffer (131072) was not large enough

### ISSUE THREAD

**Issue by kevinblighe** [r-lib/vroom#364] opened 2021-08-07 23:46 UTC
Hi, I am not directly using _vroom_ for my R / Bioconductor packages, but _vroom_ is somewhere causing 2 of my packages to report errors during the Bioconductor builds. The error is the same in both cases:

```
The size of the connection buffer (131072) was not large enough
to fit a complete line:
  * Increase it by setting `Sys.setenv("VROOM_CONNECTION_SIZE")`
--- failed re-building ‘RegParallel.Rmd’
```

- https://master.bioconductor.org/checkResults/3.13/data-experiment-LATEST/RegParallel/malbec2-buildsrc.html
- http://bioconductor.org/checkResults/devel/bioc-LATEST/PCAtools/

This error just appeared relatively recently; so, I put it down to a change that has been made by _vroom_, which feeds its way back to my 2 packages via inter-dependencies.

I have tried to fix this by specifying this (setting the suggested variable `VROOM_CONNECTION_SIZE`):

- https://github.com/kevinblighe/PCAtools/blob/master/vignettes/PCAtools.Rmd#L30

I also tried to set this variable in the relevant code chunk from which the error is produced, but it makes no difference, unfortunately:

- https://github.com/kevinblighe/PCAtools/blob/master/vignettes/PCAtools.Rmd#L161-L212

Kind regards,
Kevin

**Comment by Alanocallaghan** [comment] 2021-08-12 21:59
Seeing this in `GEOquery::getGEO`:

```r
GEOquery::getGEO("GSE2990", GSEMatrix = TRUE, getGPL = FALSE)
```

Running `Sys.setenv(VROOM_CONNECTION_SIZE=500072)` fixed it for me, but I just picked that number at random. Would be good to have a higher default maybe.

**Comment by Alanocallaghan** [comment] 2021-08-12 23:07
The plot, as they say, thickens. If I `Sys.setenv(VROOM_CONNECTION_SIZE = 500000)`, I get 

```
Error: The size of the connection buffer (5) was not large enough
```

but ending in 72 is fine...

**Comment by jimhester** [comment] 2021-08-16 19:29
This is likely a duplicate of https://github.com/r-lib/vroom/issues/360, the file you are trying to read has linefeed newlines, which vroom does not support.

**Comment by Alanocallaghan** [comment] 2021-08-16 22:06
Sorry Jim but I am fairly sure (99%, based on checking `file` and `mac2unix`) that that's not the case. eg, `file table.txt` gives `ASCII text, with very long lines` and diffing the mac2unix'd file gives no diff.

Also, I think my last comment about the env var getting read as 5 rather than 500000 may be an independent bug

**Comment by jimhester** [comment] 2021-08-17 12:18
If someone can supply I minimal reproducible example, e.g. a call to `vroom::vroom()` that exhibits the issue I can look into it further. But the current reports in this thread are not actionable.

**Comment by Alanocallaghan** [comment] 2021-08-17 12:25
```r
system("wget https://ftp.ncbi.nlm.nih.gov/geo/series/GSE2nnn/GSE2990/matrix/GSE2990_series_matrix.txt.gz")

vroom::vroom(
    "GSE2990_series_matrix.txt.gz",
    delim = "\t",
    skip = 107L,
)
```

**Comment by jimhester** [comment] 2021-08-17 13:13
See the following for the explanation, this seems to be working as intended, the buffer needs to be big enough to fit the skipped data plus the first two full lines.

``` r
lines <- vroom::vroom_lines("~/data/GSE2990_series_matrix.txt.gz")

# Buffer size must be at least this big (skipped data plus first two lines) for this file
buf_size <- sum(nchar(lines[1:109]))
buf_size
#> [1] 297480

Sys.setenv(VROOM_CONNECTION_SIZE = as.integer(buf_size))
x <- vroom::vroom("~/data/GSE2990_series_matrix.txt.gz", delim = "\t", skip = 107L)
#> Rows: 22284 Columns: 190
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: "\t"
#> chr   (1): ID_REF
#> dbl (189): GSM65316, GSM65317, GSM65318, GSM65319, GSM65320, GSM65321, GSM65...
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# Environment variables are characters, and R by default formats doubles past a certain size in scientific notation when converting to character.
# vroom expects the environment variable to be an integer number and does not handle scientific notation.
Sys.setenv(VROOM_CONNECTION_SIZE = 500000)
Sys.getenv("VROOM_CONNECTION_SIZE")
#> [1] "5e+05"

Sys.setenv(VROOM_CONNECTION_SIZE = "500000")
Sys.getenv("VROOM_CONNECTION_SIZE")
#> [1] "500000"

x <- vroom::vroom("~/data/GSE2990_series_matrix.txt.gz", delim = "\t", skip = 107L)
#> Rows: 22284 Columns: 190
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: "\t"
#> chr   (1): ID_REF
#> dbl (189): GSM65316, GSM65317, GSM65318, GSM65319, GSM65320, GSM65321, GSM65...
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
```

<sup>Created on 2021-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by Alanocallaghan** [comment] 2021-08-17 13:15
Fair enough, seems reasonable. Sorry for protesting, this is not really a vroom issue after all.

**Closed** 2021-08-17 13:18 UTC
Labels: reprex
