### ISSUE TITLE
hard crash if `n_max = 0` and `col_names` a character vector

### ISSUE THREAD

**Issue by mgirlich** [r-lib/vroom#316] opened 2021-03-01 08:22 UTC
This is quite an edge case but it would still be much nicer to not crash the R session:

```r
vroom::vroom(
  I("x,y\n1,2\n3,4\n"),
  # EDIT the `col_names` argument must be a character vector like it says in the title
  # col_names = FALSE,
  col_names = c("a", "b"),
  n_max = 0
)
```

**Comment by jimhester** [comment] 2021-04-28 13:59
I can't reproduce this one with the current devel, perhaps it is already fixed?

``` r
library(vroom)

vroom(
  I("x,y\n1,2\n3,4\n"),
  col_names = FALSE,
  n_max = 0
)
#> # A tibble: 0 x 0
```

<sup>Created on 2021-04-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by mgirlich** [comment] 2021-04-29 04:38
Yes, seems to be fixed. Thanks!

**Comment by mgirlich** [comment] 2021-04-29 04:39
argh, realised the title says something different than the "reprex". It should have been

```r
vroom::vroom(
  I("x,y\n1,2\n3,4\n"),
  col_names = c("a", "b"),
  n_max = 0
)
```

**Comment by jimhester** [comment] 2021-04-29 11:38
Ah, thanks for the updated reprex, it should be fixed now.

**Closed** 2021-04-29 11:38 UTC
Labels: bug
